language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.1'
  - '7.2'

env:
    matrix:
        - DEPS=no
        - DEPS=low

before_script:
  - composer self-update
  - if [[ $DEPS = low ]]; then composer update --no-interaction --prefer-lowest; fi
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
